version: '3.8'
services:
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/bash", "/opt/src/script/build.sh", "v1.2.0"]
    volumes:
      - "/data/pgmodeler:/opt/pgmodeler"