FROM handcraftedbits/pgmodeler-builder-deps1
LABEL com.handcraftedbits.image.authors="opensource@handcraftedbits.com"
LABEL net.baotran.image.authors="contact@baotran.net"

RUN cd /opt/mxe && \
  make MXE_TARGETS='x86_64-w64-mingw32.shared' qt6-qtbase qt6-qtimageformats qt6-qtsvg && \
  rm -rf pkg .ccache

