FROM ubuntu:22.04
LABEL com.handcraftedbits.image.authors="opensource@handcraftedbits.com"
LABEL net.baotran.image.authors="contact@baotran.net"

RUN apt-get update && \
  apt-get install -y autoconf automake autopoint bash bison bzip2 flex g++ g++-multilib gettext git gperf intltool \
  libc6-dev-i386 libgdk-pixbuf2.0-dev libltdl-dev libgl-dev libssl-dev libtool-bin libxml-parser-perl lzip make openssl \
  p7zip-full patch perl python3 python3-mako python-pkg-resources ruby sed unzip wget xz-utils && \
  cd /opt && \
  git clone https://github.com/mxe/mxe.git && \
  cd mxe && \
  make MXE_TARGETS='x86_64-w64-mingw32.shared x86_64-w64-mingw32.static' cc

